apiVersion: v1
kind: Service
metadata:
  name: katm-mip
  namespace: katm
  labels:
    app: katm-mip
spec:
  type: ClusterIP
  selector:
    app: katm-mip
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
