apiVersion: v1
kind: Service
metadata:
  name: katm-ucin
  namespace: katm
  labels:
    app: katm-ucin
spec:
  type: ClusterIP
  selector:
    app: katm-ucin
  ports:
    - port: 8094
      targetPort: 8094
      protocol: TCP
      name: http
