
package uz.katm.mip.ws.citizen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GetCitizenInfoServiceNewService", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl", wsdlLocation = "file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetCitizenInfoServiceNew.wsdl")
public class GetCitizenInfoServiceNewService
    extends Service
{

    private static final URL GETCITIZENINFOSERVICENEWSERVICE_WSDL_LOCATION;
    private static final WebServiceException GETCITIZENINFOSERVICENEWSERVICE_EXCEPTION;
    private static final QName GETCITIZENINFOSERVICENEWSERVICE_QNAME = new QName("urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl", "GetCitizenInfoServiceNewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetCitizenInfoServiceNew.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETCITIZENINFOSERVICENEWSERVICE_WSDL_LOCATION = url;
        GETCITIZENINFOSERVICENEWSERVICE_EXCEPTION = e;
    }

    public GetCitizenInfoServiceNewService() {
        super(__getWsdlLocation(), GETCITIZENINFOSERVICENEWSERVICE_QNAME);
    }

    public GetCitizenInfoServiceNewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCITIZENINFOSERVICENEWSERVICE_QNAME, features);
    }

    public GetCitizenInfoServiceNewService(URL wsdlLocation) {
        super(wsdlLocation, GETCITIZENINFOSERVICENEWSERVICE_QNAME);
    }

    public GetCitizenInfoServiceNewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCITIZENINFOSERVICENEWSERVICE_QNAME, features);
    }

    public GetCitizenInfoServiceNewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCitizenInfoServiceNewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCitizenInfoServiceNewPortType
     */
    @WebEndpoint(name = "GetCitizenInfoServiceNewSOAP11BindingPort")
    public GetCitizenInfoServiceNewPortType getGetCitizenInfoServiceNewSOAP11BindingPort() {
        return super.getPort(new QName("urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl", "GetCitizenInfoServiceNewSOAP11BindingPort"), GetCitizenInfoServiceNewPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCitizenInfoServiceNewPortType
     */
    @WebEndpoint(name = "GetCitizenInfoServiceNewSOAP11BindingPort")
    public GetCitizenInfoServiceNewPortType getGetCitizenInfoServiceNewSOAP11BindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl", "GetCitizenInfoServiceNewSOAP11BindingPort"), GetCitizenInfoServiceNewPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCITIZENINFOSERVICENEWSERVICE_EXCEPTION!= null) {
            throw GETCITIZENINFOSERVICENEWSERVICE_EXCEPTION;
        }
        return GETCITIZENINFOSERVICENEWSERVICE_WSDL_LOCATION;
    }

}
