
package uz.katm.mip.ws.citizen;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GetCitizenInfoServiceNewPortType", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetCitizenInfoServiceNewPortType {


    /**
     * 
     * @param receive2Input
     * @return
     *     returns uz.katm.mip.ws.citizen.PinppAddressResponse
     */
    @WebMethod(action = "/mediate/ips/MOI/GetCitizenInfoServiceNew")
    @WebResult(name = "PinppAddressResponse", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl", partName = "receive2Output")
    public PinppAddressResponse receive2(
        @WebParam(name = "PinppAddress", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetCitizenInfoServiceNew/GetCitizenInfoServiceNew.wsdl", partName = "receive2Input")
        PinppAddress receive2Input);

}
