
package uz.katm.mip.ws.doc;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonDocInfoServicePortType", targetNamespace = "urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonDocInfoServicePortType {


    /**
     * 
     * @param soapMsgReceiveInput
     * @return
     *     returns uz.katm.mip.ws.doc.CEPResponse
     */
    @WebMethod(operationName = "soapMsg_Receive", action = "/mediate/ips/PC/PersonDocInfoService")
    @WebResult(name = "CEPResponse", targetNamespace = "urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl", partName = "soapMsg_ReceiveOutput")
    public CEPResponse soapMsgReceive(
        @WebParam(name = "CEPRequest", targetNamespace = "urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl", partName = "soapMsg_ReceiveInput")
        CEPRequest soapMsgReceiveInput);

}
