
package uz.katm.mip.ws.doc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PersonDocInfoServiceService", targetNamespace = "urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl", wsdlLocation = "file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/PersonDocInfoService.wsdl")
public class PersonDocInfoServiceService
    extends Service
{

    private static final URL PERSONDOCINFOSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException PERSONDOCINFOSERVICESERVICE_EXCEPTION;
    private static final QName PERSONDOCINFOSERVICESERVICE_QNAME = new QName("urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl", "PersonDocInfoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/PersonDocInfoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONDOCINFOSERVICESERVICE_WSDL_LOCATION = url;
        PERSONDOCINFOSERVICESERVICE_EXCEPTION = e;
    }

    public PersonDocInfoServiceService() {
        super(__getWsdlLocation(), PERSONDOCINFOSERVICESERVICE_QNAME);
    }

    public PersonDocInfoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONDOCINFOSERVICESERVICE_QNAME, features);
    }

    public PersonDocInfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, PERSONDOCINFOSERVICESERVICE_QNAME);
    }

    public PersonDocInfoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONDOCINFOSERVICESERVICE_QNAME, features);
    }

    public PersonDocInfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonDocInfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonDocInfoServicePortType
     */
    @WebEndpoint(name = "PersonDocInfoServiceSOAP11BindingPort")
    public PersonDocInfoServicePortType getPersonDocInfoServiceSOAP11BindingPort() {
        return super.getPort(new QName("urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl", "PersonDocInfoServiceSOAP11BindingPort"), PersonDocInfoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonDocInfoServicePortType
     */
    @WebEndpoint(name = "PersonDocInfoServiceSOAP11BindingPort")
    public PersonDocInfoServicePortType getPersonDocInfoServiceSOAP11BindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl", "PersonDocInfoServiceSOAP11BindingPort"), PersonDocInfoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONDOCINFOSERVICESERVICE_EXCEPTION!= null) {
            throw PERSONDOCINFOSERVICESERVICE_EXCEPTION;
        }
        return PERSONDOCINFOSERVICESERVICE_WSDL_LOCATION;
    }

}
