
package uz.katm.mip.ws.address;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GetAddressPortType", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetAddressPortType {


    /**
     * 
     * @param receive1Input
     * @return
     *     returns uz.katm.mip.ws.address.ResponseModel
     */
    @WebMethod(action = "/mediate/ips/MOI/GetAddress")
    @WebResult(name = "ResponseModel", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl", partName = "receive1Output")
    public ResponseModel receive1(
        @WebParam(name = "Request", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl", partName = "receive1Input")
        Request receive1Input);

}
