
package uz.katm.mip.ws.address;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GetAddressService", targetNamespace = "urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl", wsdlLocation = "file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetAddress.wsdl")
public class GetAddressService
    extends Service
{

    private static final URL GETADDRESSSERVICE_WSDL_LOCATION;
    private static final WebServiceException GETADDRESSSERVICE_EXCEPTION;
    private static final QName GETADDRESSSERVICE_QNAME = new QName("urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl", "GetAddressService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetAddress.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETADDRESSSERVICE_WSDL_LOCATION = url;
        GETADDRESSSERVICE_EXCEPTION = e;
    }

    public GetAddressService() {
        super(__getWsdlLocation(), GETADDRESSSERVICE_QNAME);
    }

    public GetAddressService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETADDRESSSERVICE_QNAME, features);
    }

    public GetAddressService(URL wsdlLocation) {
        super(wsdlLocation, GETADDRESSSERVICE_QNAME);
    }

    public GetAddressService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETADDRESSSERVICE_QNAME, features);
    }

    public GetAddressService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAddressService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAddressPortType
     */
    @WebEndpoint(name = "GetAddressSOAP11BindingPort")
    public GetAddressPortType getGetAddressSOAP11BindingPort() {
        return super.getPort(new QName("urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl", "GetAddressSOAP11BindingPort"), GetAddressPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAddressPortType
     */
    @WebEndpoint(name = "GetAddressSOAP11BindingPort")
    public GetAddressPortType getGetAddressSOAP11BindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:megaware:/mediate/ips/MOI/GetAddress/GetAddress.wsdl", "GetAddressSOAP11BindingPort"), GetAddressPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETADDRESSSERVICE_EXCEPTION!= null) {
            throw GETADDRESSSERVICE_EXCEPTION;
        }
        return GETADDRESSSERVICE_WSDL_LOCATION;
    }

}
