apiVersion: v1
kind: Service
metadata:
  name: katm-contract
  namespace: katm
  labels:
    app: katm-contract
spec:
  type: ClusterIP
  selector:
    app: katm-contract
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
