apiVersion: v1
kind: Service
metadata:
  name: katm-client
  namespace: katm
  labels:
    app: katm-client
spec:
  type: ClusterIP
  selector:
    app: katm-client
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: http
