
package uz.katm.mip.ws.tin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GetTinbyPasNumNewService", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl", wsdlLocation = "file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetTinbyPasNumNew.wsdl")
public class GetTinbyPasNumNewService
    extends Service
{

    private static final URL GETTINBYPASNUMNEWSERVICE_WSDL_LOCATION;
    private static final WebServiceException GETTINBYPASNUMNEWSERVICE_EXCEPTION;
    private static final QName GETTINBYPASNUMNEWSERVICE_QNAME = new QName("urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl", "GetTinbyPasNumNewService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetTinbyPasNumNew.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETTINBYPASNUMNEWSERVICE_WSDL_LOCATION = url;
        GETTINBYPASNUMNEWSERVICE_EXCEPTION = e;
    }

    public GetTinbyPasNumNewService() {
        super(__getWsdlLocation(), GETTINBYPASNUMNEWSERVICE_QNAME);
    }

    public GetTinbyPasNumNewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETTINBYPASNUMNEWSERVICE_QNAME, features);
    }

    public GetTinbyPasNumNewService(URL wsdlLocation) {
        super(wsdlLocation, GETTINBYPASNUMNEWSERVICE_QNAME);
    }

    public GetTinbyPasNumNewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETTINBYPASNUMNEWSERVICE_QNAME, features);
    }

    public GetTinbyPasNumNewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetTinbyPasNumNewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetTinbyPasNumNewPortType
     */
    @WebEndpoint(name = "GetTinbyPasNumNewSOAP11BindingPort")
    public GetTinbyPasNumNewPortType getGetTinbyPasNumNewSOAP11BindingPort() {
        return super.getPort(new QName("urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl", "GetTinbyPasNumNewSOAP11BindingPort"), GetTinbyPasNumNewPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetTinbyPasNumNewPortType
     */
    @WebEndpoint(name = "GetTinbyPasNumNewSOAP11BindingPort")
    public GetTinbyPasNumNewPortType getGetTinbyPasNumNewSOAP11BindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl", "GetTinbyPasNumNewSOAP11BindingPort"), GetTinbyPasNumNewPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETTINBYPASNUMNEWSERVICE_EXCEPTION!= null) {
            throw GETTINBYPASNUMNEWSERVICE_EXCEPTION;
        }
        return GETTINBYPASNUMNEWSERVICE_WSDL_LOCATION;
    }

}
