
package uz.katm.mip.ws.tin;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GetTinbyPasNumNewPortType", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetTinbyPasNumNewPortType {


    /**
     * 
     * @param rEQInput
     * @return
     *     returns uz.katm.mip.ws.tin.FormData
     */
    @WebMethod(action = "/mediate/ips/STC/GetTinbyPasNumNew")
    @WebResult(name = "FormData", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl", partName = "rEQOutput")
    public FormData rEQ(
        @WebParam(name = "GetTinbyPas", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTinbyPasNumNew/GetTinbyPasNumNew.wsdl", partName = "rEQInput")
        GetTinbyPas rEQInput);

}
