apiVersion: v1
kind: Service
metadata:
  name: katm-report
  namespace: katm
  labels:
    app: katm-report
spec:
  type: ClusterIP
  selector:
    app: katm-report
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
