apiVersion: v1
kind: Service
metadata:
  name: katm-reference
  namespace: katm
  labels:
    app: katm-reference
spec:
  type: ClusterIP
  selector:
    app: katm-reference
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
