apiVersion: v1
kind: Service
metadata:
  name: katm-system
  namespace: katm
  labels:
    app: katm-system
spec:
  type: ClusterIP
  selector:
    app: katm-system
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
      name: http
