-- KATM Platform Oracle 19c Schema Initialization
-- Run as SYS/SYSDBA

-- Create tablespace
CREATE TABLESPACE KATM_DATA
    DATAFILE '/opt/oracle/oradata/KATMDB/katm_data01.dbf' SIZE 500M
    AUTOEXTEND ON NEXT 100M MAXSIZE 5G
    SEGMENT SPACE MANAGEMENT AUTO;

-- Create users/schemas
CREATE USER katm_auth IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_client IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_claim IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_contract IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_report IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_notif IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_queue IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_scheduler IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

CREATE USER katm_mip IDENTIFIED BY "katm_pass"
    DEFAULT TABLESPACE KATM_DATA
    QUOTA UNLIMITED ON KATM_DATA;

-- Grant privileges
DECLARE
    v_users SYS.DBMS_DEBUG_VC2COLL := SYS.DBMS_DEBUG_VC2COLL(
        'katm_auth','katm_client','katm_claim','katm_contract',
        'katm_report','katm_notif','katm_queue','katm_scheduler','katm_mip'
    );
BEGIN
    FOR i IN 1..v_users.COUNT LOOP
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ' || v_users(i);
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, ' ||
            'CREATE TRIGGER, CREATE VIEW, CREATE INDEX TO ' || v_users(i);
    END LOOP;
END;
/
