-- Scheduler Service uses Quartz tables
ALTER SESSION SET CURRENT_SCHEMA = katm_scheduler;

-- Quartz tables for Oracle
CREATE TABLE QRTZ_JOB_DETAILS (
    SCHED_NAME        VARCHAR2(120) NOT NULL,
    JOB_NAME          VARCHAR2(200) NOT NULL,
    JOB_GROUP         VARCHAR2(200) NOT NULL,
    DESCRIPTION       VARCHAR2(250),
    JOB_CLASS_NAME    VARCHAR2(250) NOT NULL,
    IS_DURABLE        VARCHAR2(1)   NOT NULL,
    IS_NONCONCURRENT  VARCHAR2(1)   NOT NULL,
    IS_UPDATE_DATA    VARCHAR2(1)   NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1)   NOT NULL,
    JOB_DATA          BLOB,
    CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE QRTZ_TRIGGERS (
    SCHED_NAME     VARCHAR2(120) NOT NULL,
    TRIGGER_NAME   VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL,
    JOB_NAME       VARCHAR2(200) NOT NULL,
    JOB_GROUP      VARCHAR2(200) NOT NULL,
    DESCRIPTION    VARCHAR2(250),
    NEXT_FIRE_TIME NUMBER(13),
    PREV_FIRE_TIME NUMBER(13),
    PRIORITY       NUMBER(13),
    TRIGGER_STATE  VARCHAR2(16)  NOT NULL,
    TRIGGER_TYPE   VARCHAR2(8)   NOT NULL,
    START_TIME     NUMBER(13)    NOT NULL,
    END_TIME       NUMBER(13),
    CALENDAR_NAME  VARCHAR2(200),
    MISFIRE_INSTR  NUMBER(2),
    JOB_DATA       BLOB,
    CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE QRTZ_CRON_TRIGGERS (
    SCHED_NAME      VARCHAR2(120) NOT NULL,
    TRIGGER_NAME    VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP   VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    TIME_ZONE_ID    VARCHAR2(80),
    CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE QRTZ_FIRED_TRIGGERS (
    SCHED_NAME        VARCHAR2(120) NOT NULL,
    ENTRY_ID          VARCHAR2(140) NOT NULL,
    TRIGGER_NAME      VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP     VARCHAR2(200) NOT NULL,
    INSTANCE_NAME     VARCHAR2(200) NOT NULL,
    FIRED_TIME        NUMBER(13)    NOT NULL,
    SCHED_TIME        NUMBER(13)    NOT NULL,
    PRIORITY          NUMBER(13)    NOT NULL,
    STATE             VARCHAR2(16)  NOT NULL,
    JOB_NAME          VARCHAR2(200),
    JOB_GROUP         VARCHAR2(200),
    IS_NONCONCURRENT  VARCHAR2(1),
    REQUESTS_RECOVERY VARCHAR2(1),
    CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE QRTZ_LOCKS (
    SCHED_NAME  VARCHAR2(120) NOT NULL,
    LOCK_NAME   VARCHAR2(40)  NOT NULL,
    CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

INSERT INTO QRTZ_LOCKS VALUES ('KatmScheduler', 'STATE_ACCESS');
INSERT INTO QRTZ_LOCKS VALUES ('KatmScheduler', 'TRIGGER_ACCESS');
COMMIT;
