package uz.katm.mip.ws.debtor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-10-06T10:55:47.486+05:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://deptorservice.mibcenter.mib.uz/", name = "DebtorWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DebtorWS {

    @WebMethod
    @Action(input = "http://deptorservice.mibcenter.mib.uz/DebtorWS/getDebtorPhysicalByPinflRequest", output = "http://deptorservice.mibcenter.mib.uz/DebtorWS/getDebtorPhysicalByPinflResponse")
    @WebResult(name = "return", targetNamespace = "http://deptorservice.mibcenter.mib.uz/", partName = "return")
    public DebtorIndividualByPinflResult getDebtorPhysicalByPinfl(

        @WebParam(partName = "argument", name = "argument")
        DebtorIndividualByPinflArgument argument
    );

    @WebMethod
    @Action(input = "http://deptorservice.mibcenter.mib.uz/DebtorWS/getDebtorPhysicalRequest", output = "http://deptorservice.mibcenter.mib.uz/DebtorWS/getDebtorPhysicalResponse")
    @WebResult(name = "return", targetNamespace = "http://deptorservice.mibcenter.mib.uz/", partName = "return")
    public DebtorIndividualResult getDebtorPhysical(

        @WebParam(partName = "argument", name = "argument")
        DebtorIndividualArgument argument
    );

    @WebMethod
    @Action(input = "http://deptorservice.mibcenter.mib.uz/DebtorWS/getDebtorJuridicalRequest", output = "http://deptorservice.mibcenter.mib.uz/DebtorWS/getDebtorJuridicalResponse")
    @WebResult(name = "return", targetNamespace = "http://deptorservice.mibcenter.mib.uz/", partName = "return")
    public DebtorJuridicalResult getDebtorJuridical(

        @WebParam(partName = "argument", name = "argument")
        DebtorJuridicalArgument argument
    );
}
