package uz.katm.mip.ws.debtor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-10-06T10:55:47.883+05:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "DebtorWSService",
                  wsdlLocation = "http://deptorservice.mibcenter.mib.uz:8081/WS",
                  targetNamespace = "http://deptorservice.mibcenter.mib.uz/")
public class DebtorWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://deptorservice.mibcenter.mib.uz/", "DebtorWSService");
    public final static QName DebtorWSPort = new QName("http://deptorservice.mibcenter.mib.uz/", "DebtorWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://deptorservice.mibcenter.mib.uz:8081/WS");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DebtorWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://deptorservice.mibcenter.mib.uz:8081/WS");
        }
        WSDL_LOCATION = url;
    }

    public DebtorWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DebtorWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DebtorWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DebtorWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DebtorWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DebtorWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DebtorWS
     */
    @WebEndpoint(name = "DebtorWSPort")
    public DebtorWS getDebtorWSPort() {
        return super.getPort(DebtorWSPort, DebtorWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DebtorWS
     */
    @WebEndpoint(name = "DebtorWSPort")
    public DebtorWS getDebtorWSPort(WebServiceFeature... features) {
        return super.getPort(DebtorWSPort, DebtorWS.class, features);
    }

}
