apiVersion: v1
kind: Service
metadata:
  name: katm-registry
  namespace: katm
  labels:
    app: katm-registry
spec:
  type: ClusterIP
  selector:
    app: katm-registry
  ports:
    - port: 8092
      targetPort: 8092
      protocol: TCP
      name: http
