
package uz.katm.mip.ws.tax;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "GetTaxInfobyPinService", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl", wsdlLocation = "file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetTaxInfobyPin.wsdl")
public class GetTaxInfobyPinService
    extends Service
{

    private static final URL GETTAXINFOBYPINSERVICE_WSDL_LOCATION;
    private static final WebServiceException GETTAXINFOBYPINSERVICE_EXCEPTION;
    private static final QName GETTAXINFOBYPINSERVICE_QNAME = new QName("urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl", "GetTaxInfobyPinService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Project/katm-platform/services/mip-service/src/main/resources/wsdl/GetTaxInfobyPin.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETTAXINFOBYPINSERVICE_WSDL_LOCATION = url;
        GETTAXINFOBYPINSERVICE_EXCEPTION = e;
    }

    public GetTaxInfobyPinService() {
        super(__getWsdlLocation(), GETTAXINFOBYPINSERVICE_QNAME);
    }

    public GetTaxInfobyPinService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETTAXINFOBYPINSERVICE_QNAME, features);
    }

    public GetTaxInfobyPinService(URL wsdlLocation) {
        super(wsdlLocation, GETTAXINFOBYPINSERVICE_QNAME);
    }

    public GetTaxInfobyPinService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETTAXINFOBYPINSERVICE_QNAME, features);
    }

    public GetTaxInfobyPinService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetTaxInfobyPinService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetTaxInfobyPinPortType
     */
    @WebEndpoint(name = "GetTaxInfobyPinSOAP11BindingPort")
    public GetTaxInfobyPinPortType getGetTaxInfobyPinSOAP11BindingPort() {
        return super.getPort(new QName("urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl", "GetTaxInfobyPinSOAP11BindingPort"), GetTaxInfobyPinPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetTaxInfobyPinPortType
     */
    @WebEndpoint(name = "GetTaxInfobyPinSOAP11BindingPort")
    public GetTaxInfobyPinPortType getGetTaxInfobyPinSOAP11BindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl", "GetTaxInfobyPinSOAP11BindingPort"), GetTaxInfobyPinPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETTAXINFOBYPINSERVICE_EXCEPTION!= null) {
            throw GETTAXINFOBYPINSERVICE_EXCEPTION;
        }
        return GETTAXINFOBYPINSERVICE_WSDL_LOCATION;
    }

}
