
package uz.katm.mip.ws.tax;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "GetTaxInfobyPinPortType", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetTaxInfobyPinPortType {


    /**
     * 
     * @param receive1Input
     * @return
     *     returns uz.katm.mip.ws.tax.GetTaxInfobyPinRes
     */
    @WebMethod(action = "/mediate/ips/STC/GetTaxInfobyPin")
    @WebResult(name = "getTaxInfobyPinRes", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl", partName = "receive1Output")
    public GetTaxInfobyPinRes receive1(
        @WebParam(name = "getTaxInfobyPinReq", targetNamespace = "urn:megaware:/mediate/ips/STC/GetTaxInfobyPin/GetTaxInfobyPin.wsdl", partName = "receive1Input")
        GetTaxInfobyPinReq receive1Input);

}
